
# Clear
rm(list = ls())

# Setup
################################################################################

# Packages
library(sf)
library(rgdal)
library(rgeos)
library(lwgeom)
library(ggrepel)
library(shiny)
library(shinythemes)
library(tidyverse)
library(RColorBrewer)

# Directories
datadir <- "data" # for actual app
codedir <- "code"  # for actual app
# datadir <- "shiny_apps/wc_landings/data" # when testing
# codedir <- "shiny_apps/wc_landings/code" # when testing

# Source code
sapply(list.files(codedir), function(x) source(file.path(codedir, x)))

# Read port data
ports_ca <- read.csv(file.path(datadir, "port_key_v3.csv"), as.is=T)

# Read landings data
# data_ca_orig <- readRDS(file.path(datadir, "1928_2019_CA_landings_by_port_species.Rds"))
data_ca_orig <- read.csv(file.path(datadir, "CDFW_2000_2019_landings_by_port_expanded.csv"), as.is=T)
data_noaa_orig <- readRDS(file.path(datadir, "NOAA_1950_2019_wc_landings_by_state_species.Rds"))

# Read country shapefiles
load(file.path(datadir, "country_shapefiles.Rdata"))

# Read RAM ata
data_ram_status <- readRDS(file=file.path(datadir, "RAM_WC_status_data.Rds"))
data_ram_sr <- readRDS(file=file.path(datadir, "RAM_WC_recruitment_data.Rds"))
data_ram_sp <- readRDS(file=file.path(datadir, "RAM_WC_production_data.Rds"))

# Read OceanAdapt data
data_oa <- readRDS(file.path(datadir, "OA_1977_2018_distribution_shifts.Rds"))


# Prepare data
################################################################################

# Ports and order
areas_do <- c("Eureka", "Fort Bragg", "Bodega Bay", "San Francisco", "Monterey", "Morro Bay", "Santa Barbara", "Los Angeles", "San Diego")

# Prepare CA marine landings data
data_ca <- data_ca_orig %>% 
  # Reduce to:
  filter(presentation=="whole" & level=="species" & area %in% areas_do) %>% # environment=="marine" & 
  # Add a nice species name
  mutate(species_label=paste0(comm_name, " (", sci_name, ")")) %>%
  # Arrange port complex
  mutate(area=factor(area, levels=areas_do))

# OA species-region key
spp_key_oa <- data_oa %>% 
  select(region, species_label) %>% 
  unique() %>% 
  arrange(region, species_label)

# RAM species-stock key
key_ram <- data_ram_status %>% 
  select(species_label, comm_name, species, area) %>% 
  unique() %>% 
  arrange(species_label)


# Parameters
################################################################################

# Species
species_ca <- sort(unique(data_ca$species_label))
species_ram <- sort(unique(data_ram_status$species_label))
species_oa <- sort(unique(data_oa$species_label))

# Regions
regions <- c("West Coast", "Gulf of Alaska", "Aleutian Islands", "Eastern Bering Sea")

# Base theme
base_theme <- theme(axis.text=element_text(size=14),
                    axis.title=element_text(size=16),
                    legend.text=element_text(size=14),
                    legend.title=element_text(size=16),
                    strip.text=element_text(size=16),
                    plot.subtitle=element_text(size=18),
                    plot.title=element_text(size=16),
                    panel.grid.major = element_blank(), 
                    panel.grid.minor = element_blank(),
                    panel.background = element_blank(), 
                    axis.line = element_line(colour = "black"))

# User interface
################################################################################

# User interface
ui <- navbarPage("West Coast Fisheries & Climate Change Explorer",
                 
   # DISTRIBUTION SHIFTS                             
   tabPanel("Distribution shifts",
            
      # Title 
      h3("Shifts in species distributions"),
      
      # Intro text
      p("Marine fish and invertebrates are expected to shift their distributions due to climate change. As waters warm, marine species are expected to shift into deeper and/or more poleward waters to track their preferred temperatures. These shifts can complicate stock assessments when species shift outside the area of the scientific survey program. These shifts can complicate management when a species shifts into new jurisdictions. Finally, these shifts can impact fishing communities unable to follow the shifting resource."),
      
      p("Here, we illustrate evidence for species distribution shifts XXX marine fish and invertebrate species spanning the US. West Coast, Gulf of Alaska, Aleutian Islands, and Bering Sea regions using data generated by the OceanAdapt project (https://oceanadapt.rutgers.edu/). The OceanAdapt team used trawl survey data collected by NOAA, DFO, and other agencies to describe shifts in the center of biomass of over 650 fish and invertebrate species in eight regions nationally."),
      
      # Select species
      p("To begin exploring shifts in distribution, select a species from the drop down menu below."), 
      selectInput(inputId = "species_oa", label = "Select a species:", 
                     choices = species_oa,  multiple = F),
      br(),
      
      # Select region and plot time series
      radioButtons(inputId = "region_oa", label="Select a region:", choices = regions, inline=T),
      plotOutput(outputId = "plot_oa_dist_shift", width=1000, height=375),
      br(),
      
      # Plot map
      plotOutput(outputId = "plot_oa_dist_shift_map", width=1000, height=1000),
      br()
            
   ),
                 
  # PRODUCTIVITY SHIFTS                            
  tabPanel("Productivity shifts",
           
    # Title 
    h3("Shifts in population productivity"),
    
    # Intro text
    p("Climate change is expected to impact the productivity of marine fish and invertebrate populations thereby impacting the amount of fish that can be sustainably harvested. These impacts can be either positive or negative depending on the direction and magnitude of change and the position of a population within its environmental niche.
"), 
    p("In this section, we explore the evidence for historical climate change impacts on West Coast fisheries productivity. The vulnerability of populations to environmental change is heightened with decreasing population health and we begin with a visualization of historical and current stock status. We then examine the impact of historical climate change on the recruitment of juvenile fish into the population. We then examine the impact on total production, which encompasses impacts of recruitment, mortality, and body growth. "),
    p("To begin exploring shiftis in productivity, select a species from the drop down menu below."),
    
    # Select species
    selectizeInput(inputId = "species_ram", label = "Select a species:", 
                   choices = species_ram,  multiple = F, options = NULL),
    br(),
    
    # Plot stock status
    h4("Stock status"),
    p("The vulnerability of fish populations to climate change is impacted by the health of the population. Well-managed fisheries with healthy stock status and age/size structure are more resilient to climate change than poorly-managed fisheries of depleted status and truncated age/size structures."),
    p("In the figures below, we illustrate stock status over time. B/BMSY represents the ratio of estimated biomass to the biomass target (B/BMSY) and U/UMSY represents the ratio of estimated fishing mortality to the fishing mortality target. B/BMSY values near 1.0 indicate maximally fished stocks. Values greater than 1.0 indicate underfished stocks and value less than 1.0 indicate overfished stocks. In the Unites States, overfished stocks are legally defined as having B/BMSY less than 0.5. F/FMSY values greater than 1.0 indicate that overfishing is occurring and values less than 1.0 indicate that overfishing is not occurring."),
    radioButtons(inputId = "stock_ram", label="Select a stock:", choices = "temp", inline=T),
    plotOutput(outputId = "plot_ram_status", width=1000, height=350),
    br(),
    
    # Plot recruitment
    h4("Recruitment"),
    p("In the figure below, we visualize and quantify the impact of historical temperature change on recruitment. The first two panels show time series of (A) biomass and (B) recruitment estimated from the stock assessment model. The third panels shows the (C) stock-recruit relationship and the impact of temperature in driving deviations from the expected stock-recruit relationship. The fourth panel shows the stock-recruit residuals over time related to temperature and the final panel shows the model estimated change in recruitment potential as a result of temperature change."),
    plotOutput(outputId = "plot_ram_recruitment", width=1000, height=350),
    br(),
    
    # Plot production
    h4("Production"),
    p("In the figure below, we visualize and quantify the impact of historical temperature change on total production. The first two panels show time series of (A) biomass and (B) catch which are the ingredients required to calculate (C) surplus production (i.e., change in population size in the absence of harvest. The fourth panel shows (D) production as a function of biomass and temperature. The fifth panel shows the  (D) production residuals over time related to temperature and the final panel shows the (E) model estimated change in maximum sustainable yield over time as a result of temperature change."),
    plotOutput(outputId = "plot_ram_production", width=1000, height=700),
    br()
    
  ),

  # Landings                           
  tabPanel("Landings shifts",
   
   # Title 
   h3("Explore landings by species"),    
           
    # Select species
    p("Only landings of marine species with taxonomic identification to the species level are shown here. In other words, freshwater species (from the Sacramento Delta and other Inland Waters) and species in broad taxonomic groups (e.g., unspecified crustacean) are excluded."),
    p("The taxonomic resolution of reported landings has increased through time and the absence of landings can occur not because a fish or invertebrate was not landeded but because its landings were recorded in a broader taxonomic group."),
    selectizeInput(inputId = "species", label = "Select a species:", 
                   choices = species_ca,  multiple = F, options = NULL),
    br(),
    
    # RANK METRICS
    h4("Economic importance of the commercial fishery"),
    
    # Plot recent rank scatterplot
    p("The figure below shows the average annual landings and value over the last 5 years (2015-2019) for the selected species compared to the other species landed in California during this time period. Values (USD) have not been adjusted to account for inflation."),
    plotOutput(outputId = "plot_rank_scatterplot", width=700, height=600),
    br(),
    
    # Plot rank state-wide and by port complex
    p("The figure below shows the rank of the selected species relative to other commercial species over time. The rank represents fisheries from largest to smallest in terms of total landings and total value, i.e., a rank of 1 represents the largest fishery."),
    plotOutput(outputId = "plot_rank_by_species", width=1000, height=500), 
    br(),
    
    # TREND METRICS
    h4("Trends in commercial fishery landings and value"),
    
    # Plot landings time series by port complex
    p("The figure below shows the trends in annual landings and value for the selected species by port complex. Values (USD) have not been adjusted to account for inflation."),
    plotOutput(outputId = "plot_landings_ts_by_area", width=1000, height=500),
    br(),
    
    # Plot landings time series by port complex
    p("The figure below shows the trends in the proportion of annual landings and value for the selected species coming from each port complex. Values (USD) have not been adjusted to account for inflation."),
    plotOutput(outputId = "plot_landings_ts_by_area_prop", width=1000, height=500), 
    br(),
    
    # GEOGRAPHY OF LANDINGS
    h4("Shifting geography of commercial landings"),
    
    # Plot map of landings
   p("The figure below shows the average annual landings over the last 5 years (2015-2019) for the selected species by port. In some years and for some species, landings are attributed to an “All Other Ports” category to maintain confidentiality. These landings are plotted at the centroid of the areas ports."),
   plotOutput(outputId = "plot_landings_by_port_map", width=800, height=1000),
   br(),
   
    # Plot latitude shift through time
   p("The figure below shows how the landings-weighted latitude of the selected species has shifted through time. This calculation excludes the landings attributed to the “All Other Ports” category."),
   plotOutput(outputId = "plot_landings_lat_shift", width=800, height=300),
   br(),
           
  ),
  
  # Closures and disasters                             
  tabPanel("Closures and disasters")


)


# Server
################################################################################

# Server
server <- function(input, output, session){
  
  # RAM
  #################################
  
  # Update RAM stock options
  observe({
    updateRadioButtons(session, "stock_ram", inline=T,
                       choices = as.character(key_ram$area[key_ram$species_label==input$species_ram]))
  })
  
  # Plot RAM stock staus
  output$plot_ram_status <- renderPlot({
    g <- plot_ram_status(dataset=data_ram_status, species = input$species_ram, 
                         stock=input$stock_ram, base_theme=base_theme)
    g
  })
  
  # Plot RAM recruitment
  output$plot_ram_recruitment <- renderPlot({
    g <- plot_ram_recruitment(dataset=data_ram_sr, species = input$species_ram, 
                              stock=input$stock_ram, base_theme=base_theme)
    g
  })
  
  # Plot RAM production
  output$plot_ram_production <- renderPlot({
    g <- plot_ram_production(dataset=data_ram_sp, species = input$species_ram, 
                              stock=input$stock_ram, base_theme=base_theme)
    g
  })
  
  # OceanAdapt
  #################################
  
  # Update OA region options
  observe({
    updateRadioButtons(session, "region_oa", inline=T,
                       choices = as.character(spp_key_oa$region[spp_key_oa$species_label==input$species_oa]))
  })
  
  # Plot distribution shift
  output$plot_oa_dist_shift <- renderPlot({
    g <- plot_oa_dist_shift(dataset=data_oa, species = input$species_oa, region = input$region_oa, 
                            base_theme=base_theme)
    g
  })
  
  # Plot distribution shift
  output$plot_oa_dist_shift_map <- renderPlot({
    g <- plot_oa_dist_shift_map(dataset=data_oa, species = input$species_oa, region = input$region_oa, 
                                base_theme=base_theme, usa=usa, mexico=mexico, canada=canada)
    g
  })
  
  # Landings data
  #################################
  
  # Plot rank scatterplot
  output$plot_rank_scatterplot <- renderPlot({
    g <- plot_rank_scatterplot(dataset=data_ca, species_label = input$species, 
                               base_theme=base_theme)
    g
  })
  
  # Plot rank state-wide and by port
  output$plot_rank_by_species <- renderPlot({
    g <- plot_rank_by_species(dataset=data_ca, species_label = input$species, 
                              base_theme=base_theme)
    g
  })
  
  # Plot landings time series by port complex
  output$plot_landings_ts_by_area <- renderPlot({
    g <- plot_landings_ts_by_area(dataset=data_ca, noaa=data_noaa_orig, species_label = input$species, 
                                  base_theme=base_theme)
    g
  })
  
  # Plot landings time series by port complex (proprotional)
  output$plot_landings_ts_by_area_prop <- renderPlot({
    g <- plot_landings_ts_by_area_prop(dataset=data_ca, species_label = input$species, 
                                       base_theme=base_theme)
    g
  })
  
  # Plot landings by port map
  output$plot_landings_by_port_map <- renderPlot({
    g <- plot_landings_by_port_map(dataset=data_ca, ports=ports_ca, species_label = input$species, 
                                   base_theme=base_theme, usa=usa, mexico=mexico)
    g
  })
  
  # Plot landings lat shift
  output$plot_landings_lat_shift <- renderPlot({
    g <- plot_landings_lat_shift(dataset=data_ca, ports=ports_ca, species_label = input$species, 
                                 base_theme=base_theme)
    g
  })
  
}

shinyApp(ui = ui, server = server)
